fix: escape keys and use -r for yq raw output

diff --git a/bin/tmux-nerd-font-window-name b/bin/tmux-nerd-font-window-name
--- a/bin/tmux-nerd-font-window-name
+++ b/bin/tmux-nerd-font-window-name
@@ -1,8 +1,8 @@
 #!/usr/bin/env bash
 
 if ! command -v yq >/dev/null 2>&1; then
-	echo "$1 ⚠︎ yq missing"
-	exit 1
+  echo "$1 ⚠︎ yq missing"
+  exit 1
 fi
 
 NAME="$1"
@@ -12,41 +12,41 @@ DEFAULT_CONFIG="$CURRENT_DIR/defaults.yml"
 USER_CONFIG="$HOME/.config/tmux/tmux-nerd-font-window-name.yml"
 
 get_config_value() {
-	local key=$1
-	local value
-	if test -f "$USER_CONFIG"; then
-		value="$(yq "$key" "$USER_CONFIG")"
-		if [ "$value" == "null" ]; then # get default config value
-			value="$(yq "$key" "$DEFAULT_CONFIG")"
-		fi
-	else
-		value="$(yq "$key" "$DEFAULT_CONFIG")"
-	fi
-	echo "$value"
+  local key=$1
+  local value
+  if test -f "$USER_CONFIG"; then
+    value="$(yq -r "$key" "$USER_CONFIG")"
+    if [ "$value" == "null" ]; then # get default config value
+      value="$(yq -r "$key" "$DEFAULT_CONFIG")"
+    fi
+  else
+    value="$(yq -r "$key" "$DEFAULT_CONFIG")"
+  fi
+  echo "$value"
 }
 
-ICON="$(get_config_value ".icons.\"$NAME\"")"
+ICON="$(get_config_value ".icons[\"$NAME\"]")"
 
 if [ "$ICON" == "null" ]; then
-	FALLBACK_ICON="$(get_config_value '.config.fallback-icon')"
-	ICON="$FALLBACK_ICON"
+  FALLBACK_ICON="$(get_config_value '.config["fallback-icon"]')"
+  ICON="$FALLBACK_ICON"
 fi
 
 if [ "$PANES" -gt 1 ]; then
-	MULTI_PANE_ICON="$(get_config_value '.config.multi-pane-icon')"
-	if [ "$MULTI_PANE_ICON" != "null" ]; then
-		ICON="$MULTI_PANE_ICON $ICON"
-	fi
+  MULTI_PANE_ICON="$(get_config_value '.config["multi-pane-icon"]')"
+  if [ "$MULTI_PANE_ICON" != "null" ]; then
+    ICON="$MULTI_PANE_ICON $ICON"
+  fi
 fi
 
-SHOW_NAME="$(get_config_value '.config.show-name')"
+SHOW_NAME="$(get_config_value '.config["show-name"]')"
 if [ "$SHOW_NAME" = true ]; then
-	ICON_POSITION="$(get_config_value '.config.icon-position')"
-	if [ "$ICON_POSITION" == "right" ]; then
-		ICON="$NAME $ICON"
-	else
-		ICON="$ICON $NAME"
-	fi
+  ICON_POSITION="$(get_config_value '.config["icon-position"]')"
+  if [ "$ICON_POSITION" == "right" ]; then
+    ICON="$NAME $ICON"
+  else
+    ICON="$ICON $NAME"
+  fi
 fi
 
 echo "$ICON"
